### ISSUE TITLE
publish to ethpm

### ISSUE THREAD

**Issue by ghost** [swarmcity/sc-dappcontracts#8]
publish package to https://www.ethpm.com/registry

- ethpm.json file

**Comment by ghost** [comment]
#9 Make a PR

https://www.ethpm.com/registry/packages/27
0.0.1 contains tokens from sc-dappcontracts-production
0.0.2-pre is built from sc-dappcontracts

both versions have issues importing sub-project dependencies from zeppelin.  `/app/contracts/installed_contracts/swarmcity/contracts/DealForTwo.sol` depends on `/app/contracts/installed_contracts/swarmcity/installed_contracts/zeppelin/contracts/ownership/Ownable.sol` etc....

non-relative (absolute) path-addressing of Libraries might help.  like `/opt/eth//installed_contracts/zeppelin/contracts/...`  or `/lib/installed_contracts/zeppelin/contracts/...`.  But relative paths in solidity imports is easier to use in a dev env.

**Comment by sponnet** [comment]
merged..
